<?php
include_once("index.scss");
include_once("SelectImgFromTag.scss");
include_once("InstructionPopUp.scss");
include_once("Loader.scss");
include_once("Login.scss");
include_once("Display.scss");
include_once("Nav.scss");
include_once("show.scss");
include_once("UserPanelSettings.scss");
?>
