<?php
include_once("index.scss");
include_once("./components/create_update_user/SelectImgFromTag.scss");
include_once("./components/Instruction_pop_up/InstructionPopUp.scss");
include_once("./components/Loader/Loader.scss");
include_once("./components/login_create_portal/Login.scss");
include_once("./components/login_user/Display.scss");
include_once("./components/NavBar/Nav.scss");
include_once("./components/root/show.scss");
include_once("./components/User_Logged_In/UserPanelSettings.scss");
?>
